
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager

spring.datasource.username=postgres

spring.datasource.password=lavanya13

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.application.name=taskmanager

jwt.secret=mySecretKey123456789012345678901234567890

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=paidilavanya00@gmail.com

spring.mail.password=kfmv sjqg nkun wuoh

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

app.reminder.sender=paidilavanya00@gmail.com

APP_FRONTEND_URL=http://localhost:3000

